// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5VkWJu3Fzbf91Cd4umXBp5ehG7TsZv8',
    appId: '1:754988776980:android:3036e4ba27ce4fd331b101',
    messagingSenderId: '754988776980',
    projectId: 'cs308-202102',
    storageBucket: 'cs308-202102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF1SASb_jOMuXmvLqpGIHaRKkXRetoK9Y',
    appId: '1:754988776980:ios:308208d34f496f0031b101',
    messagingSenderId: '754988776980',
    projectId: 'cs308-202102',
    storageBucket: 'cs308-202102.appspot.com',
    androidClientId: '754988776980-2vkbuof130idffq4l635ugu86ea3l92u.apps.googleusercontent.com',
    iosClientId: '754988776980-2v8s6hbu53pse6ovqqr3l3cnum0opj7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoeshop',
  );
}
